// src/pages/Top.vue
<template>
  <app-header></app-header>
  <div class="py-3 px-5 pt-8 mx-auto text-center text-gray-700 leading-7 max-w-3xl">
    <div class="p-3 mb-4 text-blue-700 text-lg font-semibold border-blue-700 border-2 rounded">
      「LeacTion!」は、勉強会やセミナーで発表者と参加者をつなぐ、<br />オンラインコメントツールです
    </div>
    <div class="mb-10">
      <router-link to="/new">
        <button
          class="w-full my-6 px-5 py-2 bg-blue-700 text-white text-lg font-semibold tracking-widest rounded"
        >
          イベントを登録する
        </button>
      </router-link>
    </div>
    <div class="py-10 mb-20 px-4 bg-blue-100 about">
      <img src="images/baloon.png" class="w-24 mb-3 mx-auto" />
      <h2 class="mb-10 text-2xl font-semibold">LeacTion! とは？</h2>
      <div class="max-w-lg mx-auto text-sm">
        勉強会やセミナーで、スマートフォンやパソコンを使い、リアルタイムに質問やコメントを投稿できるサービスです。<br />
        オフラインのセミナーや勉強会はもちろん、オンラインイベントやオンライン・オフライン同時開催イベントでも利用できます。
      </div>
    </div>
    <div>
      <h2 class="mb-10 text-lg font-semibold">
        LeacTion! でイベントが盛り上がる
        <p class="text-3xl">３つの理由</p>
      </h2>
      <div class="pl-2 w-auto text-sm inline-block">
        <h3 class="mb-4 text-lg font-semibold underline">参加者も管理者もログイン不要！</h3>
        <div class="max-w-lg mx-auto mb-16">
          参加者は、イベントページを開くだけですぐにコメントや質問を投稿できます。<br />
          管理者も、面倒な会員登録やログインは不要。イベントにパスワードを設定するだけで、後から編集も可能です。
        </div>
        <h3 class="mb-4 text-lg font-semibold underline">質問やコメントに「いいね！」できる</h3>
        <div class="max-w-lg mx-auto mb-16">
          発表者は「いいね！」ボタンで「自分も気になる！」「自分もそう思う」と意思表明できます。
          発表中や質問タイムに、特に参加者の関心がある質問・コメントを見つけやすくなります。
        </div>
        <h3 class="mb-4 text-lg font-semibold underline">
          発表枠ごとに、質問やコメントを投稿できる
        </h3>
        <div class="max-w-lg mx-auto mb-8">
          あらかじめ登録しておいた発表枠を切り替えるだけで、特定の発表に対するコメントを投稿できます。
          複数の発表・登壇があるイベントでも、誰宛の質問なのかすぐにわかるので、よりスムーズに進行できます。
        </div>
      </div>
    </div>
    <div>
      <router-link to="/new">
        <button
          class="w-full my-6 px-5 py-2 bg-blue-700 text-white text-lg font-semibold tracking-widest rounded"
        >
          イベントを登録する
        </button>
      </router-link>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Top",
  setup() {
    return {};
  },
});
</script>

<style scoped>
.about {
  width: 100vw;
  position: relative;
  left: 50%;
  transform: translateX(-50%);
}
</style>

// src/pages/Top.tsx
import { useNavigate } from "@solidjs/router";
import { Button, useTheme } from "@suid/material";
import Box from "@suid/material/Box";
import Container from "@suid/material/Container";
import Paper from "@suid/material/Paper";
import Stack from "@suid/material/Stack";
import Typography from "@suid/material/Typography";
import { VoidComponent } from "solid-js";

// @ref: https://ja.vitejs.dev/guide/assets.html#importing-asset-as-url
import baloonUrl from "~/assets/baloon.png";
import { MediumSizeTextParagraph } from "~/components/typographies";
import { LargeSizeText } from "~/components/typographies";

const Top: VoidComponent = () => {
  const navigate = useNavigate();
  const theme = useTheme();
  const { light: primaryLightColor, main: primaryMainColor } = theme.palette.primary;
  const textColor = theme.palette.grey[700];

  return (
    <Container
      maxWidth="2sm"
      sx={{
        padding: "32px 20px 12px",
        margin: "0 auto",
        textAlign: "center",
      }}
    >
      <Box marginBottom="32px">
        <Paper
          elevation={0}
          sx={{
            padding: "12px",
            border: `2px solid ${primaryMainColor}`,
          }}
        >
          <LargeSizeText color={primaryMainColor}>
            「LeacTion!」は、勉強会やセミナーで発表者と参加者をつなぐ、
            <br />
            オンラインコメントツールです
          </LargeSizeText>
        </Paper>
      </Box>

      <Box marginBottom="40px">
        <Button variant="contained" fullWidth onClick={() => navigate("/new")}>
          イベントを作成する
        </Button>
      </Box>

      <Box marginBottom="80px">
        <Paper
          elevation={0}
          square={true}
          sx={{
            backgroundColor: primaryLightColor,
            padding: "40px 16px",
            position: "relative",
            width: "100vw",
            left: "50%",
            transform: "translateX(-50%)",
          }}
        >
          <Stack>
            <Box
              component="img"
              src={baloonUrl}
              alt="コメントアイコン"
              marginX="auto"
              marginBottom="12px"
              width="96px"
            />
            <Typography
              variant="h6"
              marginBottom="40px"
              color={textColor}
              sx={{
                fontWeight: "bold",
              }}
            >
              LeacTion! とは？
            </Typography>
            <Box maxWidth={512} marginX="auto">
              <MediumSizeTextParagraph>
                勉強会やセミナーで、スマートフォンやパソコンを使い、リアルタイムに質問やコメントを投稿できるサービスです。
                <br />
                オフラインのセミナーや勉強会はもちろん、オンラインイベントやオンライン・オフライン同時開催イベントでも利用できます。
              </MediumSizeTextParagraph>
            </Box>
          </Stack>
        </Paper>
      </Box>

      <Box marginBottom="40px">
        <Paper elevation={0}>
          <Box marginBottom="40px">
            <LargeSizeText>LeacTion! でイベントが盛り上がる</LargeSizeText>
            <Typography variant="h5" fontWeight="bold" color={textColor}>
              ３つの理由
            </Typography>
          </Box>
          <Stack spacing={8} maxWidth={512} marginX="auto">
            <Box>
              <Typography
                variant="subtitle1"
                fontWeight="bold"
                marginBottom="16px"
                color={textColor}
                sx={{
                  textDecoration: "underline",
                }}
              >
                参加者はログイン不要！
              </Typography>
              <MediumSizeTextParagraph>
                ログインが必要なのはイベント管理者だけ。
                <br />
                イベントの参加者はイベントページを開くだけですぐにコメントや質問を投稿できます。
              </MediumSizeTextParagraph>
            </Box>
            <Box>
              <Typography
                variant="subtitle1"
                fontWeight="bold"
                marginBottom="16px"
                color={textColor}
                sx={{
                  textDecoration: "underline",
                }}
              >
                質問やコメントに「いいね！」できる
              </Typography>
              <MediumSizeTextParagraph>
                発表者は「いいね！」ボタンで「自分も気になる！」「自分もそう思う」と意思表明できます。
                発表中や質問タイムに、特に参加者の関心がある質問・コメントを見つけやすくなります。
              </MediumSizeTextParagraph>
            </Box>
            <Box>
              <Typography
                variant="subtitle1"
                fontWeight="bold"
                marginBottom="16px"
                color={textColor}
                sx={{
                  textDecoration: "underline",
                }}
              >
                発表枠ごとに、質問やコメントを投稿できる
              </Typography>
              <MediumSizeTextParagraph>
                発表者は「いいね！」ボタンで「自分も気になる！」「自分もそう思う」と意思表明できます。
                発表中や質問タイムに、特に参加者の関心がある質問・コメントを見つけやすくなります。
              </MediumSizeTextParagraph>
            </Box>
          </Stack>
        </Paper>
      </Box>

      <Box marginBottom="8px">
        <Button variant="contained" fullWidth onClick={() => navigate("/new")}>
          イベントを作成する
        </Button>
      </Box>
    </Container>
  );
};

export default Top;
