// src/components/EventHeader.vue
<template>
  <header class="bg-blue-700 text-white">
    <nav>
      <div class="flex items-center p-1 md:p-3">
        <div class="flex-shrink-0 pr-5 hidden sm:block">
          <h1 class="text-3xl">LeacTion!</h1>
        </div>
        <div class="flex-grow flex items-center">
          <div class="flex-grow text-center">
            <h2 class="text-2xl">{{ eventTitle }}</h2>
          </div>
          <div v-if="eventHashtag.length > 0" class="hidden md:block">
            <a
              :href="`https://twitter.com/intent/tweet/?hashtags=${eventHashtag}`"
              target="_blank"
              rel="noopener noreferrer"
              ><button class="twitter-share-button bg-white hover:bg-gray-100">
                <font-awesome-icon :icon="['fab', 'twitter']" /> tweet #{{ eventHashtag }}
              </button></a
            >
          </div>
          <div>
            <button
              type="button"
              class="text-3xl px-2"
              title="メニュー"
              @click="showMenu = !showMenu"
            >
              <font-awesome-icon :icon="['fas', 'bars']" />
            </button>
          </div>
        </div>
      </div>
      <ul
        v-if="showMenu"
        class="md:flex md:items-center md:justify-between container mx-auto px-2 md:px-0 md:py-2"
      >
        <li v-if="eventHashtag.length > 0" class="w-full md:hidden border-t py-2 pl-6">
          <a
            :href="`https://twitter.com/intent/tweet/?hashtags=${eventHashtag}`"
            target="_blank"
            rel="noopener noreferrer"
            ><button class="twitter-share-button bg-white hover:bg-gray-100">
              <font-awesome-icon :icon="['fab', 'twitter']" /> tweet #{{ eventHashtag }}
            </button></a
          >
        </li>
        <li class="w-full md:w-1/3 md:text-center border-t md:border-t-0 md:border-r">
          <a class="block w-full my-2 md:my-0 py-2 px-6 cursor-pointer" @click="openShareModal">
            <font-awesome-icon :icon="['fas', 'share-alt']" class="mr-2" />イベントをシェアする</a
          >
        </li>
        <li class="w-full md:w-1/3 md:text-center border-t md:border-t-0 md:border-r">
          <router-link :to="`/event/${eventId}/edit`" class="block w-full my-2 md:my-0 py-2 px-6">
            <font-awesome-icon :icon="['fas', 'edit']" class="w-10 mr-2" />イベントを編集する
          </router-link>
        </li>
        <li class="w-full md:w-1/3 md:text-center border-t md:border-t-0">
          <router-link to="/" class="block w-full my-2 md:my-0 py-2 px-6">
            <font-awesome-icon :icon="['fas', 'plus-square']" class="mr-2" />新規イベントを作成する
          </router-link>
        </li>
      </ul>
    </nav>
    <modal v-show="showShareModal">
      <div class="w-full px-4">
        <h3 class="text-center text-2xl font-bold mb-4">イベントをシェアする</h3>
        <div class="flex justify-center mb-4">
          <div class="p-3 border-2 rounded-lg">
            <img :src="qrcodeUrl.href" />
          </div>
        </div>
        <div class="mb-4">
          <div class="w-full inline-flex">
            <input
              id="share-url"
              ref="share-url"
              class="p-2 border-2 rounded-l flex-grow"
              type="text"
              name="share-url"
              :value="currentUrl"
              readonly
            />
            <button type="button" class="px-4 py-2 rounded-r bg-gray-300 border-2" @click="copyUrl">
              <font-awesome-icon :icon="['fas', 'clipboard']" /><span class="hidden md:inline ml-2"
                >URLをコピーする</span
              >
            </button>
          </div>
        </div>
        <div class="flex items-center justify-between">
          <div class="items-center">
            <a :href="tweetUrl.href" target="_blank" rel="noopener">
              <button class="bg-blue-400 text-white px-3 py-2 rounded">
                <font-awesome-icon :icon="['fab', 'twitter']" /> Tweet
              </button>
            </a>
          </div>
          <div>
            <button
              type="button"
              class="bg-green-500 text-white p-2 rounded"
              @click="showShareModal = false"
            >
              閉じる
            </button>
          </div>
        </div>
      </div>
    </modal>
  </header>
</template>

<script lang="ts">
import { defineComponent, computed, ref } from "vue";
import Swal from "sweetalert2";

import Modal from "./Modal.vue";

export default defineComponent({
  name: "EventHeader",
  props: {
    eventId: {
      type: String,
      required: true,
    },
    eventTitle: {
      type: String,
      required: true,
    },
    eventHashtag: {
      type: String,
      required: true,
    },
  },
  components: { Modal },
  setup(props, context) {
    const showMenu = ref(false);
    const showShareModal = ref(false);
    const openShareModal = () => {
      showMenu.value = false;
      showShareModal.value = true;
    };
    const currentUrl = location.href;

    const copyUrl = () => {
      navigator.clipboard.writeText(currentUrl).then(() => {
        Swal.fire({
          title: "URLをコピーしました！",
          position: "top-end",
          toast: true,
          showConfirmButton: false,
          timer: 1000,
        });
      });
    };

    // create QR Code image via API. ref http://goqr.me/api/
    const qrcodeUrl = new URL("https://api.qrserver.com/v1/create-qr-code/");
    qrcodeUrl.searchParams.append("data", currentUrl);
    qrcodeUrl.searchParams.append("size", "300x300");
    const tweetUrl = computed(() => {
      const url = new URL("https://twitter.com/intent/tweet");
      url.searchParams.append("text", `LeacTion で「${props.eventTitle}」にリアクションしよう！`);
      url.searchParams.append("url", currentUrl);
      url.searchParams.append(
        "hashtags",
        props.eventHashtag.length > 0 ? `${props.eventHashtag},LeacTion` : "LeacTion"
      );
      return url;
    });

    return { showMenu, showShareModal, openShareModal, qrcodeUrl, tweetUrl, currentUrl, copyUrl };
  },
});
</script>

<style lang="postcss" scoped>
.twitter-share-button {
  color: #1b95e0;
  border-radius: 3px;
  padding: 0.25em 0.5em;
}
</style>

// src/features/event/components/EventHeader.tsx
import { useNavigate } from "@solidjs/router";
import {
  AddCircle,
  Close,
  ContentCopy,
  Edit,
  Info,
  Menu as MenuIcon,
  Share,
} from "@suid/icons-material";
import {
  AppBar,
  Box,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Divider,
  IconButton,
  ListItemIcon,
  ListItemText,
  Menu,
  MenuItem,
  Skeleton,
  Stack,
  Toolbar,
  Typography,
} from "@suid/material";
import { VoidComponent, Switch, Match, createSignal, Show } from "solid-js";
import toast from "solid-toast";
import { TwitterIcon } from "~/components/icons";
import { RouterLink } from "~/components/links";

type EventHeaderProps = {
  eventId?: string;
  eventName?: string;
  eventHashTag?: string;
  isEditable: boolean;
};

export const EventHeader: VoidComponent<EventHeaderProps> = (props) => {
  const [anchorEl, setAnchorEl] = createSignal<HTMLElement | null>(null);
  const menuOpen = () => !!anchorEl();
  const [shareDialogOpen, setShareDialogOpen] = createSignal(false);
  const navigate = useNavigate();

  const eventUrl = () => new URL(`/event/${props.eventId}`, location.href).toString();

  const qrcodeUrl = () => {
    const u = new URL("https://api.qrserver.com/v1/create-qr-code/");
    u.searchParams.append("data", eventUrl());
    u.searchParams.append("size", "300x300");
    return u.toString();
  };

  const shareOnTwitter = () => {
    const u = new URL("https://twitter.com/intent/tweet");
    u.searchParams.append("text", `LeacTion!で「${props.eventName}」にリアクションしよう！`);
    u.searchParams.append("url", eventUrl());
    u.searchParams.append(
      "hashtags",
      props.eventHashTag ? `${props.eventHashTag},LeacTion` : "LeacTion"
    );
    window.open(u, "_blank");
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(eventUrl());
    toast("コピーしました", { icon: <Info /> });
  };

  return (
    <AppBar position="static" sx={{ padding: 0 }}>
      <Toolbar>
        <Show when={props.eventId} fallback={<Skeleton variant="text" />}>
          <Box>
            <Typography variant="h5" sx={{ fontWeight: "bold", marginRight: "1em" }}>
              <RouterLink href="/">LeacTion!</RouterLink>
            </Typography>
          </Box>
          <Box flexGrow={1} textAlign="center">
            <Typography variant="h5" sx={{ fontWeight: "bold" }}>
              {props.eventName}
            </Typography>
          </Box>
          <IconButton onClick={(e) => setAnchorEl(e.currentTarget)}>
            <MenuIcon fontSize="large" sx={{ color: "white" }} />
          </IconButton>
          <Menu open={menuOpen()} anchorEl={anchorEl()} onClose={() => setAnchorEl(null)}>
            <MenuItem
              onClick={() => {
                setShareDialogOpen(true);
                setAnchorEl(null);
              }}
            >
              <ListItemIcon>
                <Share fontSize="small" />
              </ListItemIcon>
              <ListItemText>共有する</ListItemText>
            </MenuItem>
            <Divider />
            <Switch>
              <Match when={!props.isEditable}>
                <MenuItem onClick={() => navigate(`/event/${props.eventId}/manager-request`)}>
                  <ListItemIcon>
                    <Edit fontSize="small" />
                  </ListItemIcon>
                  <ListItemText>共同管理者になる</ListItemText>
                </MenuItem>
              </Match>
              <Match when={props.isEditable}>
                <MenuItem onClick={() => navigate(`/event/${props.eventId}/edit`)}>
                  <ListItemIcon>
                    <Edit fontSize="small" />
                  </ListItemIcon>
                  <ListItemText>イベントを編集する</ListItemText>
                </MenuItem>
              </Match>
            </Switch>
            <Divider />
            <MenuItem onClick={() => navigate("/new")}>
              <ListItemIcon>
                <AddCircle fontSize="small" />
              </ListItemIcon>
              <ListItemText>新しいイベントを作る</ListItemText>
            </MenuItem>
          </Menu>
        </Show>
      </Toolbar>
      <Dialog
        open={shareDialogOpen()}
        maxWidth="lg"
        onBackdropClick={() => setShareDialogOpen(false)}
      >
        <DialogTitle>
          <Typography variant="h6">イベントを共有する</Typography>
          <IconButton
            onClick={() => setShareDialogOpen(false)}
            sx={{ position: "absolute", top: 8, right: 8 }}
          >
            <Close />
          </IconButton>
        </DialogTitle>
        <DialogContent>
          <Box
            sx={{
              textAlign: "center",
              padding: "2em",
              border: "2px solid gray",
              borderRadius: "5%",
            }}
          >
            <img src={qrcodeUrl()} alt="イベントページのQRコード" width={300} height={300} />
          </Box>
        </DialogContent>
        <DialogActions>
          <Stack gap={1} width="100%">
            <Box>
              <Button
                variant="outlined"
                fullWidth
                startIcon={<ContentCopy />}
                onClick={copyToClipboard}
              >
                URLをクリップボードにコピー
              </Button>
            </Box>
            <Box>
              <Button
                variant="contained"
                fullWidth
                startIcon={<TwitterIcon />}
                onClick={shareOnTwitter}
              >
                Twitterでツイートする
              </Button>
            </Box>
          </Stack>
        </DialogActions>
      </Dialog>
    </AppBar>
  );
};
